@startuml nanoKON2-Setup

title クラス図

namespace W0NYV {

    namespace nanoKON2 {

        class ControllerCounts {
        }

        class NanoKON2Handler {
            - _input : PlayerInput
        }
        note bottom: Input SystemからのMIDIを受け取り、イベント発火

        class NanoKON2Model {
            + model : Model
            + guiModel : Model
        }

        class NanoKON2Presenter {
            - _nanoKON2Handler : NanoKON2Handler
            - _nanoKON2Model : NanoKON2Model
            - _slider : Slider
        }
        note bottom: 結び付けくん

        class NanoKON2EventSubscriber {
            - _subscribeObjects : List<SubscribeObject>
        }

        class Model {
            + sliderValueList : ReactiveCollection
        }

        class FloatReactiveCollection {}

        class Slider {}

        class Knob {}

        class Button {}

        Model <-- NanoKON2Model 
        FloatReactiveCollection <-- Model

        NanoKON2Model <-- NanoKON2Handler
        NanoKON2Model <- NanoKON2Presenter
        NanoKON2Model <-- NanoKON2EventSubscriber
        
        ControllerCounts <-- NanoKON2EventSubscriber
        ControllerCounts <-- Model
        ControllerCounts <-- NanoKON2Handler

        Slider <-- NanoKON2Presenter
        Knob <-- NanoKON2Presenter
        Button <-- NanoKON2Presenter

    }

    class HogeHoge{}
    note bottom: 最終的にMIDIの値を受け取るクラス

    HogeHoge <-- W0NYV.nanoKON2.NanoKON2EventSubscriber

}

@enduml